/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package consumer.project;

public class AppB {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new AppB().getGreeting());
    }
}
